---
title: "Code of Conduct"
site: distill::distill_website
output_dir: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The CHOP R User Group brings together a diverse audience of learners and users for community events such as workshops, talks, and discussions. Our goal is to make our events safe, inclusive, and accessible to all participants. We are dedicated to providing a harassment-free experience for participants at all of our events, whether they are held in person or virtually. While at CHOP R User Group events or related ancillary or social events, any participants, including members, speakers, attendees, volunteers, and anyone else, should not engage in harassment in any form.

This Code of Conduct may be revised by the CHOP R User Group at any time and the terms are non-negotiable. Your registration for or attendance at any CHOP R User Group event, whether it's held in person or virtually, indicates your agreement to abide by this policy and its terms.

## Expected Behavior

We strive to create a learning environment where all participants feel safe to share ideas, take risks, ask questions, and communicate their experiences to others. We expect all participants to engage in this environment respectfully and acknowledge the many diverse perspectives, identities, skill levels, abilities, etc. of their fellow participants.

All event participants, whether they are attending an in-person event or a virtual event, are expected to behave in accordance with professional standards, with both this Code of Conduct as well as their respective employer's policies governing appropriate workplace behavior and applicable laws.

## Unacceptable Behavior

Harassment will not be tolerated in any form, whether in person or virtually, including, but not limited to, harassment based on gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or any other status protected by laws in which the event is being held. Harassment includes the use of abusive, offensive or degrading language, intimidation, stalking, harassing photography or recording, inappropriate physical contact, sexual imagery and unwelcome sexual advances or requests for sexual favors. Any report of harassment at one of our events, whether in person or virtual, will be addressed immediately. Participants asked to stop any harassing behavior are expected to comply immediately. Anyone who witnesses or is subjected to unacceptable behavior should notify a conference organizer at once.

Speakers should not use sexual language, images, or any language or images that would constitute harassment as defined above in their talks.

Individuals who participate (or plan to participate) in CHOP R User Group events, whether it's an in-person event or a virtual event, should conduct themselves at all times in a manner that comports with both the letter and spirit of this policy prohibiting harassment and abusive behavior, whether before, during or after the event. This includes statements made in social media postings, online publications, text messages, and all other forms of electronic communication.

## Consequences of Unacceptable Behavior

If a participant engages in harassing behavior, whether in person or virtually, the event organizers may take any action they deem appropriate depending on the circumstances, ranging from issuance of a warning to the offending individual to expulsion from the event. The CHOP R User Group reserves the right to exclude any participant found to be engaging in harassing behavior from participating in any further CHOP R User Group events.

If a participant (or individual wishing to participate in a CHOP R User Group event, in-person and/or virtual), through postings on social media or other online publications or another form of electronic communication, engages in conduct that violates this policy, whether before, during or after an event, the CHOP R User Group may take appropriate corrective action, which could include imposing a temporary or permanent ban on an individual’s participation in future events.

## What To Do If You Witness or Are Subject To Unacceptable Behavior

If you are being harassed, notice that someone else is being harassed, or have any other concerns relating to harassment, please contact the event organizer immediately. 

## Incident Response

We pledge to respond to harassment reports quickly and thoroughly. As referenced above, if a participant engages in harassing behavior, whether in-person or virtually, the event organizers may take any action they deem appropriate, ranging from issuance of a warning to the offending individual to expulsion from the event, depending on the circumstances. The CHOP R User Group reserves the right to exclude any participant found to be engaging in harassing behavior from participating in any further events.

## Pre-Event Concerns

If you are planning to attend an upcoming event, whether in-person or virtually and have concerns regarding another individual who may be present, please contact the event organizer. 